# Generated by Django 5.2.4 on 2025-12-29 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("saving", "0002_savingrecord"),
    ]

    operations = [
        migrations.DeleteModel(
            name="MoodRecord",
        ),
    ]
